"""Requirement to test traceability, read from the source of the suite.

One module, two consumers. The meta layer imports it to fail the build when a
requirement has no test, and the site builder imports it to publish the
traceability table. That is deliberate: a published table generated by
different code from the gate that enforces it can disagree with the gate, and
the table is the thing a reviewer trusts.

Everything here reads files. Nothing imports the test modules, so collecting
traceability cannot be affected by a test that fails to import.
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TESTS_ROOT = REPO_ROOT / "tests"
REQUIREMENTS = REPO_ROOT / "docs" / "requirements.md"
TEST_DESIGN = REPO_ROOT / "docs" / "test-design.md"

REQ_ID = re.compile(r"REQ-\d+(?:\.\d+[a-z]?)?")
LAYERS = ("unit", "contract", "integration", "meta")

GAPS_HEADING = "## Stated gaps"
OPEN_QUESTIONS_HEADING = "## Open questions"


@dataclass(frozen=True)
class TestCase:
    """One test function, as the traceability table sees it."""

    node_id: str
    name: str
    layer: str
    summary: str
    covers: tuple[str, ...]
    endpoint: str | None = None
    reason: str = ""


@dataclass(frozen=True)
class RequirementRow:
    """One row of the published table: a requirement and everything about it."""

    requirement: str
    cases: tuple[TestCase, ...] = ()
    gap: bool = False
    layers: tuple[str, ...] = field(default=())

    @property
    def status(self) -> str:
        """Four states, and the difference between the last two is the point.

        COVERED       tests cover it and nothing about it is declared missing
        PARTIAL       tested, and something about it is declared missing
        DECLARED GAP  no test, and the test design says so and says why
        NOT COVERED   no test and no explanation, which fails the build

        A declared gap is not a pass. It is an honest hole that somebody wrote
        down before the suite existed, and it is published as such. Only the
        last state is a defect in the suite.
        """
        if self.cases and self.gap:
            return "PARTIAL"
        if self.cases:
            return "COVERED"
        if self.gap:
            return "DECLARED GAP"
        return "NOT COVERED"

    @property
    def traced(self) -> bool:
        """True when the requirement has a test or a written reason it has none."""
        return bool(self.cases) or self.gap

    @property
    def endpoints(self) -> tuple[str, ...]:
        """Endpoints exercised by the cases that cover this requirement."""
        seen = [case.endpoint for case in self.cases if case.endpoint]
        return tuple(dict.fromkeys(seen))


def _docstring_field(doc: str, label: str, labels: tuple[str, ...]) -> str:
    """The value of a `Label: value` line, joined across wrapped lines."""
    lines = [line.strip() for line in doc.splitlines()]
    for index, line in enumerate(lines):
        if not line.startswith(f"{label}:"):
            continue
        value = [line[len(label) + 1 :].strip()]
        for continuation in lines[index + 1 :]:
            if not continuation or any(
                continuation.startswith(f"{other}:") for other in labels
            ):
                break
            value.append(continuation)
        return " ".join(value).strip()
    return ""


def _string_constants(tree: ast.Module) -> dict[str, str]:
    """Module level `NAME = "value"` assignments.

    The endpoint markers reference constants rather than repeating literals, so
    resolving them here is what lets this module stay import free.
    """
    constants: dict[str, str] = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if isinstance(target, ast.Name) and isinstance(node.value, ast.Constant):
            if isinstance(node.value.value, str):
                constants[target.id] = node.value.value
    return constants


def _endpoint_of(node: ast.FunctionDef, constants: dict[str, str]) -> str | None:
    """The endpoint an `@pytest.mark.endpoint(...)` marker names, if any."""
    for decorator in node.decorator_list:
        if not isinstance(decorator, ast.Call):
            continue
        function = decorator.func
        if not (isinstance(function, ast.Attribute) and function.attr == "endpoint"):
            continue
        if not decorator.args:
            continue
        argument = decorator.args[0]
        if isinstance(argument, ast.Constant) and isinstance(argument.value, str):
            return argument.value
        if isinstance(argument, ast.Name):
            return constants.get(argument.id)
    return None


def test_cases(tests_root: Path | None = None) -> tuple[TestCase, ...]:
    """Every test function in the suite, with what it says about itself."""
    root = TESTS_ROOT if tests_root is None else tests_root
    labels = ("Layer", "Covers", "Why this layer")
    cases: list[TestCase] = []

    for path in sorted(root.rglob("test_*.py")):
        layer = next((part for part in path.parts if part in LAYERS), "unknown")
        tree = ast.parse(path.read_text(encoding="utf-8"))
        constants = _string_constants(tree)
        relative = path.relative_to(REPO_ROOT)
        for node in ast.walk(tree):
            if not (isinstance(node, ast.FunctionDef) and node.name.startswith("test_")):
                continue
            doc = ast.get_docstring(node) or ""
            summary = doc.strip().splitlines()[0] if doc.strip() else ""
            cases.append(
                TestCase(
                    node_id=f"{relative}::{node.name}",
                    name=node.name,
                    layer=_docstring_field(doc, "Layer", labels) or layer,
                    summary=summary,
                    covers=tuple(
                        dict.fromkeys(
                            REQ_ID.findall(_docstring_field(doc, "Covers", labels))
                        )
                    ),
                    endpoint=_endpoint_of(node, constants),
                    reason=_docstring_field(doc, "Why this layer", labels),
                )
            )
    return tuple(cases)


def requirement_ids(requirements: Path | None = None) -> tuple[str, ...]:
    """Every requirement ID in the requirements document, in document order."""
    text = (REQUIREMENTS if requirements is None else requirements).read_text(
        encoding="utf-8"
    )
    return tuple(dict.fromkeys(REQ_ID.findall(text)))


def stated_gaps(test_design: Path | None = None) -> tuple[str, ...]:
    """Requirement IDs named in the stated gaps section of the test design."""
    text = (TEST_DESIGN if test_design is None else test_design).read_text(encoding="utf-8")
    start = text.index(GAPS_HEADING)
    end = text.index(OPEN_QUESTIONS_HEADING)
    return tuple(dict.fromkeys(REQ_ID.findall(text[start:end])))


def gap_notes(test_design: Path | None = None) -> tuple[str, ...]:
    """The stated gaps as prose, one paragraph per gap, for publication."""
    text = (TEST_DESIGN if test_design is None else test_design).read_text(encoding="utf-8")
    section = text[text.index(GAPS_HEADING) : text.index(OPEN_QUESTIONS_HEADING)]
    paragraphs = [
        " ".join(block.split())
        for block in section.split("\n\n")
        if block.strip().startswith("**")
    ]
    return tuple(paragraphs)


def rows(
    cases: tuple[TestCase, ...] | None = None,
    requirements: tuple[str, ...] | None = None,
    gaps: tuple[str, ...] | None = None,
) -> tuple[RequirementRow, ...]:
    """The traceability table: one row per requirement, in document order."""
    cases = test_cases() if cases is None else cases
    requirements = requirement_ids() if requirements is None else requirements
    gaps = stated_gaps() if gaps is None else gaps

    table = []
    for requirement in requirements:
        covering = tuple(case for case in cases if requirement in case.covers)
        table.append(
            RequirementRow(
                requirement=requirement,
                cases=covering,
                gap=requirement in gaps,
                layers=tuple(dict.fromkeys(case.layer for case in covering)),
            )
        )
    return tuple(table)


def claimed_requirements(cases: tuple[TestCase, ...] | None = None) -> tuple[str, ...]:
    """Every requirement ID any test claims to cover."""
    cases = test_cases() if cases is None else cases
    claimed: dict[str, None] = {}
    for case in cases:
        for requirement in case.covers:
            claimed[requirement] = None
    return tuple(claimed)


def claimed_endpoints(cases: tuple[TestCase, ...] | None = None) -> dict[str, list[str]]:
    """Endpoint to the node IDs of the tests marked as exercising it."""
    cases = test_cases() if cases is None else cases
    claims: dict[str, list[str]] = {}
    for case in cases:
        if case.endpoint:
            claims.setdefault(case.endpoint, []).append(case.node_id)
    return claims


def layer_counts(cases: tuple[TestCase, ...] | None = None) -> dict[str, int]:
    """How many test functions live at each layer.

    Counted before parametrisation, so this is the number of cases written
    rather than the number of cases run. The site labels it as such.
    """
    cases = test_cases() if cases is None else cases
    counts = dict.fromkeys(LAYERS, 0)
    for case in cases:
        counts[case.layer] = counts.get(case.layer, 0) + 1
    return counts
