"""Requirement to test traceability, read from the source of the suite.

One module, two consumers. The meta layer imports it to fail the build when a
requirement has no test, and the site builder imports it to publish the
traceability table. That is deliberate: a published table generated by
different code from the gate that enforces it can disagree with the gate, and
the table is the thing a reviewer trusts.

Everything here reads files. Nothing imports the test modules, so collecting
traceability cannot be affected by a test that fails to import.
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TESTS_ROOT = REPO_ROOT / "tests"
REQUIREMENTS = REPO_ROOT / "docs" / "requirements.md"
TEST_DESIGN = REPO_ROOT / "docs" / "test-design.md"

REQ_ID = re.compile(r"REQ-\d+(?:\.\d+[a-z]?)?")
LAYERS = ("unit", "contract", "integration", "meta")

GAPS_HEADING = "## Stated gaps"
OPEN_QUESTIONS_HEADING = "## Open questions"
GAP_ENTRY = re.compile(r"^### (GAP-\d+): (.+)$", re.MULTILINE)
FIELD = re.compile(r"^\*\*(Requirements|Coverage|Guarded by|Reason):\*\*", re.MULTILINE)

COVERAGE_NONE = "none"
COVERAGE_PARTIAL = "partial"
MINIMUM_REASON = 120


@dataclass(frozen=True)
class TestCase:
    """One test function, as the traceability table sees it."""

    node_id: str
    name: str
    layer: str
    summary: str
    covers: tuple[str, ...]
    endpoint: str | None = None
    reason: str = ""
    case_id: str = ""
    expects: int | None = None
    priority: str = ""
    kind: str = ""
    preconditions: str = ""
    steps: str = ""
    expected_result: str = ""


@dataclass(frozen=True)
class Gap:
    """One declared gap, as the test design states it.

    A gap is a written decision, not a mention. An entry without a reason
    declares nothing, which is what stops a pasted requirement ID from turning
    an untested rule into an accepted one.
    """

    id: str
    title: str
    requirements: tuple[str, ...]
    coverage: str
    reason: str
    guarded_by: str = ""

    @property
    def declares_no_coverage(self) -> bool:
        """True when this entry claims the requirements have no tests at all."""
        return self.coverage == COVERAGE_NONE

    @property
    def problems(self) -> list[str]:
        """Everything structurally wrong with this entry."""
        faults = []
        if self.coverage not in (COVERAGE_NONE, COVERAGE_PARTIAL):
            faults.append(f"{self.id}: coverage is {self.coverage!r}")
        if len(self.reason) < MINIMUM_REASON:
            faults.append(f"{self.id}: the reason is too short to be a reason")
        if not self.title.strip():
            faults.append(f"{self.id}: no title")
        return faults


@dataclass(frozen=True)
class RequirementRow:
    """One row of the published table: a requirement and everything about it."""

    requirement: str
    cases: tuple[TestCase, ...] = ()
    gap: bool = False
    layers: tuple[str, ...] = field(default=())

    @property
    def status(self) -> str:
        """Four states, and the difference between the last two is the point.

        COVERED       tests cover it and nothing about it is declared missing
        PARTIAL       tested, and something about it is declared missing
        DECLARED GAP  no test, and the test design says so and says why
        NOT COVERED   no test and no explanation, which fails the build

        A declared gap is not a pass. It is an honest hole that somebody wrote
        down before the suite existed, and it is published as such. Only the
        last state is a defect in the suite.
        """
        if self.cases and self.gap:
            return "PARTIAL"
        if self.cases:
            return "COVERED"
        if self.gap:
            return "DECLARED GAP"
        return "NOT COVERED"

    @property
    def traced(self) -> bool:
        """True when the requirement has a test or a written reason it has none."""
        return bool(self.cases) or self.gap

    @property
    def endpoints(self) -> tuple[str, ...]:
        """Endpoints exercised by the cases that cover this requirement."""
        seen = [case.endpoint for case in self.cases if case.endpoint]
        return tuple(dict.fromkeys(seen))


def _docstring_field(doc: str, label: str, labels: tuple[str, ...]) -> str:
    """The value of a `Label: value` line, joined across wrapped lines."""
    lines = [line.strip() for line in doc.splitlines()]
    for index, line in enumerate(lines):
        if not line.startswith(f"{label}:"):
            continue
        value = [line[len(label) + 1 :].strip()]
        for continuation in lines[index + 1 :]:
            if not continuation or any(
                continuation.startswith(f"{other}:") for other in labels
            ):
                break
            value.append(continuation)
        return " ".join(value).strip()
    return ""


def _summary(doc: str) -> str:
    """The opening sentence of a docstring, joined across the lines it wraps.

    Taking only the first physical line cut published titles mid sentence,
    which is a formatting accident showing up as a truncated claim.
    """
    lines = []
    for line in doc.strip().splitlines():
        if not line.strip():
            break
        lines.append(line.strip())
    return " ".join(lines)


def _as_status(value: str) -> int | None:
    """An `Expects:` value as a status code, or None when it is not one."""
    return int(value) if value.strip().isdigit() else None


def _string_constants(tree: ast.Module) -> dict[str, str]:
    """Module level `NAME = "value"` assignments.

    The endpoint markers reference constants rather than repeating literals, so
    resolving them here is what lets this module stay import free.
    """
    constants: dict[str, str] = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if isinstance(target, ast.Name) and isinstance(node.value, ast.Constant):
            if isinstance(node.value.value, str):
                constants[target.id] = node.value.value
    return constants


def _endpoint_of(node: ast.FunctionDef, constants: dict[str, str]) -> str | None:
    """The endpoint an `@pytest.mark.endpoint(...)` marker names, if any."""
    for decorator in node.decorator_list:
        if not isinstance(decorator, ast.Call):
            continue
        function = decorator.func
        if not (isinstance(function, ast.Attribute) and function.attr == "endpoint"):
            continue
        if not decorator.args:
            continue
        argument = decorator.args[0]
        if isinstance(argument, ast.Constant) and isinstance(argument.value, str):
            return argument.value
        if isinstance(argument, ast.Name):
            return constants.get(argument.id)
    return None


def test_cases(tests_root: Path | None = None) -> tuple[TestCase, ...]:
    """Every test function in the suite, with what it says about itself."""
    root = TESTS_ROOT if tests_root is None else tests_root
    labels = (
        "Case",
        "Expects",
        "Priority",
        "Type",
        "Preconditions",
        "Steps",
        "Expected result",
        "Layer",
        "Covers",
        "Why this layer",
    )
    cases: list[TestCase] = []

    for path in sorted(root.rglob("test_*.py")):
        layer = next((part for part in path.parts if part in LAYERS), "unknown")
        tree = ast.parse(path.read_text(encoding="utf-8"))
        constants = _string_constants(tree)
        relative = path.relative_to(REPO_ROOT)
        for node in ast.walk(tree):
            if not (isinstance(node, ast.FunctionDef) and node.name.startswith("test_")):
                continue
            doc = ast.get_docstring(node) or ""
            summary = _summary(doc)
            cases.append(
                TestCase(
                    node_id=f"{relative}::{node.name}",
                    name=node.name,
                    layer=_docstring_field(doc, "Layer", labels) or layer,
                    summary=summary,
                    covers=tuple(
                        dict.fromkeys(
                            REQ_ID.findall(_docstring_field(doc, "Covers", labels))
                        )
                    ),
                    endpoint=_endpoint_of(node, constants),
                    reason=_docstring_field(doc, "Why this layer", labels),
                    case_id=_docstring_field(doc, "Case", labels),
                    expects=_as_status(_docstring_field(doc, "Expects", labels)),
                    priority=_docstring_field(doc, "Priority", labels),
                    kind=_docstring_field(doc, "Type", labels),
                    preconditions=_docstring_field(doc, "Preconditions", labels),
                    steps=_docstring_field(doc, "Steps", labels),
                    expected_result=_docstring_field(doc, "Expected result", labels),
                )
            )
    return tuple(cases)


def requirement_ids(requirements: Path | None = None) -> tuple[str, ...]:
    """Every requirement ID in the requirements document, in document order."""
    text = (REQUIREMENTS if requirements is None else requirements).read_text(
        encoding="utf-8"
    )
    return tuple(dict.fromkeys(REQ_ID.findall(text)))


def _field(block: str, label: str) -> str:
    """One `**Label:** value` field of a gap entry, joined across wrapped lines."""
    lines = block.splitlines()
    for index, line in enumerate(lines):
        if not line.startswith(f"**{label}:**"):
            continue
        value = [line[len(label) + 5 :].strip()]
        for continuation in lines[index + 1 :]:
            if not continuation.strip() or FIELD.match(continuation):
                break
            value.append(continuation.strip())
        return " ".join(value).strip()
    return ""


def gap_entries(test_design: Path | None = None) -> tuple[Gap, ...]:
    """Every declared gap, parsed from the entries and from nothing else.

    Text under the heading that is not inside an entry is prose. It declares
    nothing, whichever requirement IDs it happens to contain. That is what stops
    a pasted ID from converting an untested requirement into an accepted one.
    """
    text = (TEST_DESIGN if test_design is None else test_design).read_text(encoding="utf-8")
    if GAPS_HEADING not in text:
        return ()
    end = (
        text.index(OPEN_QUESTIONS_HEADING) if OPEN_QUESTIONS_HEADING in text else len(text)
    )
    section = text[text.index(GAPS_HEADING) : end]

    entries = []
    matches = list(GAP_ENTRY.finditer(section))
    for index, match in enumerate(matches):
        stop = matches[index + 1].start() if index + 1 < len(matches) else len(section)
        block = section[match.end() : stop]
        entries.append(
            Gap(
                id=match.group(1),
                title=match.group(2).strip(),
                requirements=tuple(
                    dict.fromkeys(REQ_ID.findall(_field(block, "Requirements")))
                ),
                coverage=_field(block, "Coverage").lower(),
                reason=" ".join(_field(block, "Reason").split()),
                guarded_by=_field(block, "Guarded by"),
            )
        )
    return tuple(entries)


def stated_gaps(test_design: Path | None = None) -> tuple[str, ...]:
    """Requirement IDs declared as a gap by a well formed entry."""
    declared: dict[str, None] = {}
    for gap in gap_entries(test_design):
        if gap.problems:
            continue
        for requirement in gap.requirements:
            declared[requirement] = None
    return tuple(declared)


def open_questions(test_design: Path | None = None) -> tuple[tuple[str, str], ...]:
    """The open questions, as (headline, body) pairs, for publication.

    Published rather than left in the file, because a question only visible to
    whoever opens the repository is not flagged, it is filed.
    """
    text = (TEST_DESIGN if test_design is None else test_design).read_text(encoding="utf-8")
    if OPEN_QUESTIONS_HEADING not in text:
        return ()
    section = text[text.index(OPEN_QUESTIONS_HEADING) :]
    questions = []
    for block in section.split("\n\n"):
        stripped = block.strip()
        if not stripped.startswith("**"):
            continue
        joined = " ".join(stripped.split())
        closing = joined.find("**", 2)
        headline = joined[2:closing].strip() if closing > 0 else joined
        body = joined[closing + 2 :].strip() if closing > 0 else ""
        questions.append((headline, body))
    return tuple(questions)


def rows(
    cases: tuple[TestCase, ...] | None = None,
    requirements: tuple[str, ...] | None = None,
    gaps: tuple[str, ...] | None = None,
) -> tuple[RequirementRow, ...]:
    """The traceability table: one row per requirement, in document order."""
    cases = test_cases() if cases is None else cases
    requirements = requirement_ids() if requirements is None else requirements
    gaps = stated_gaps() if gaps is None else gaps

    table = []
    for requirement in requirements:
        covering = tuple(case for case in cases if requirement in case.covers)
        table.append(
            RequirementRow(
                requirement=requirement,
                cases=covering,
                gap=requirement in gaps,
                layers=tuple(dict.fromkeys(case.layer for case in covering)),
            )
        )
    return tuple(table)


def claimed_requirements(cases: tuple[TestCase, ...] | None = None) -> tuple[str, ...]:
    """Every requirement ID any test claims to cover."""
    cases = test_cases() if cases is None else cases
    claimed: dict[str, None] = {}
    for case in cases:
        for requirement in case.covers:
            claimed[requirement] = None
    return tuple(claimed)


def claimed_endpoints(cases: tuple[TestCase, ...] | None = None) -> dict[str, list[str]]:
    """Endpoint to the node IDs of the tests marked as exercising it."""
    cases = test_cases() if cases is None else cases
    claims: dict[str, list[str]] = {}
    for case in cases:
        if case.endpoint:
            claims.setdefault(case.endpoint, []).append(case.node_id)
    return claims


def layer_counts(cases: tuple[TestCase, ...] | None = None) -> dict[str, int]:
    """How many test functions live at each layer.

    Counted before parametrisation, so this is the number of cases written
    rather than the number of cases run. The site labels it as such.
    """
    cases = test_cases() if cases is None else cases
    counts = dict.fromkeys(LAYERS, 0)
    for case in cases:
        counts[case.layer] = counts.get(case.layer, 0) + 1
    return counts
